languages:
  bn:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  de:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  es:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  fr:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  ja:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  ru:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  th:
    prompt: |
      {question}
      Solve the above math question in English, and enclose the final number at the end of the response in $\\boxed{{}}$.
  en:
    prompt: |
      {question}
      Solve the above math question, and enclose the final number at the end of the response in $\\boxed{{}}$.
