languages:
  bn:
    prompt: |
      Problem: {question}
      Translate the problem from Bengali into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  de:
    prompt: |
      Problem: {question}
      Translate the problem from German into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  es:
    prompt: |
      Problem: {question}
      Translate the problem from Spanish into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  fr:
    prompt: |
      Problem: {question}
      Translate the problem from French into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  ja:
    prompt: |
      Problem: {question}
      Translate the problem from Japanese into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  ru:
    prompt: |
      Problem: {question}
      Translate the problem from Russian into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  th:
    prompt: |
      Problem: {question}
      Translate the problem from Thai into English. Then solve the problem and enclose the final numeric answer in $\boxed{{}}$.
  en:
    prompt: |
      Problem: {question}
      Solve the problem and enclose the final numeric answer in $\boxed{{}}$.
