languages:
  bn:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation: 
  de:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation: 
  es:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation:  
  fr:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation: 
  ja:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation: 
  ru:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation: 
  sw:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation:  
  th:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
      Translation:
  en:
    prompt: |
      Answer the question, and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
