languages:
  bn:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  de:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  es:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  fr:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  ja:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  ru:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  th:
    prompt: |
      Translate the question into English, then answer it in English and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
  en:
    prompt: |
      Answer the question, and enclose the final number at the end of the response in $\\boxed{{}}$.
      Question: {question}
